spring:
  application:
    name: msgw-zuul1

# 设置超时
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
logging:
  file: /tsf-demo-logs/${spring.application.name}/root.log
  level:
    root: INFO
tct:
  enabled: false
zuul:
  sensitive-headers: 