server:
  port: 18110
spring:
  application:
    name: task-schedule-demo
  profiles:
    active: prod
logging:
  file: /var/log/${spring.application.name}/${spring.application.name}.log
tct:
  enabled: true
  client:
    properties:
      task.max.threads: 1000
      task.core.threads: 2
      thread.pool.type: FIXED